[package]
name = "unique-kmers"
version = "0.1.1"
authors = ["Claudia C. Weber"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
needletail = "0.4"
fnv = "1.0.7"
csv = "1.1"
clap ="3"
itertools = "0.10.0"
